spring:
  application:
    name: yhkz-hotel
  profiles:
    active: prod
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      password: ${ENV_DB_PRODUCT_PSWD}
      url: jdbc:mysql://${ENV_DB_HOST}/product_base${ENV_JDBC_PARAMS}
      username: ${ENV_DB_PRODUCT_USER}
      filter:
        stat:
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 1000
        wall:
          config:
            multi-statement-allow: true
      initial-size: 5
      max-active: 50
      max-pool-prepared-statement-per-connection-size: -1
      max-wait: -1
      min-evictable-idle-time-millis: 300000
      min-idle: 5
      pool-prepared-statements: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      enabled: true
      resolve-lazily: true
      max-file-size: 100MB
      max-request-size: 100MB

# server
server:
  http2:
    enabled: true
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

shiro:
  enabled: true

yhkz:
  hotel:
    redis:
      timeout: 6
      jedis:
        pool:
          max-active: 1000
          max-wait: -1ms
          max-idle: 10
          min-idle: 5

cors:
  enabled: true
  paths:
    - pattern: /**
      allow-credentials: false
      allowed-methods: "*"
      allowed-headers: "*"
      allowed-origins: "*"
      max-age: 1728000
